# Generated by Django 4.1.1 on 2023-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PublicKey',
            field=models.FileField(blank=True, upload_to='', verbose_name='Публичный ключ'),
        ),
        migrations.AddField(
            model_name='user',
            name='SecretKey',
            field=models.FileField(blank=True, upload_to='', verbose_name='Секретный ключ'),
        ),
    ]
