# Generated by Django 4.1.7 on 2023-05-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_publickey_user_secretkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='SecretKey',
        ),
    ]
