# Generated by Django 3.2.12 on 2023-05-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('data', 'Дата-Квантум'), ('it', 'IT-Квантум'), ('robot', 'Робо-Квантум'), ('hightech', 'Хайтек'), ('geo', 'Гео-Квантум'), ('shah', 'Шахматы'), ('other', 'Другое'), ('kvant', 'Кванториум')], default='', max_length=30, verbose_name='Должность'),
        ),
    ]
