# Generated by Django 4.1.7 on 2023-05-30 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона (Через +7)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('data', 'Дата-Квантум'), ('it', 'IT-Квантум'), ('robot', 'Робо-Квантум'), ('hightech', 'Хайтек'), ('geo', 'Гео-Квантум'), ('shah', 'Шахматы'), ('other', 'Другое'), ('kvant', 'Кванториум')], default='', max_length=30, verbose_name='Должность'),
        ),
    ]
