# Generated by Django 4.1.7 on 2023-05-21 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0005_alter_sigdoc_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='signature',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sigdoc',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='document.document'),
        ),
        migrations.AlterField(
            model_name='sigdoc',
            name='signaturer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sig', to=settings.AUTH_USER_MODEL),
        ),
    ]
