# Generated by Django 4.2.1 on 2023-05-23 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0006_alter_document_signature_alter_sigdoc_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigdoc',
            name='signaturer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='signaturer', to=settings.AUTH_USER_MODEL),
        ),
    ]
